# Generated by Django 4.1.1 on 2022-09-22 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('postado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=40)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.regiao')),
            ],
        ),
    ]
