# Generated by Django 4.1.1 on 2022-09-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regiao',
            new_name='Região',
        ),
    ]
