# Generated by Django 4.1.1 on 2022-09-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_regiao_região'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Região',
            new_name='Region',
        ),
    ]
