# Generated by Django 4.1.1 on 2022-09-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_região_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
